# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Kotlin & KSP compilation performance
kotlin.code.style=official
kotlin.compiler.execution.strategy=daemon
kotlin.daemon.jvmargs=-Xmx2048m -XX:+UseParallelGC
kotlin.incremental=true
ksp.incremental=true
ksp.incremental.intermodule=true

# Android Gradle Plugin build performance
android.nonTransitiveRClass=true
android.enableR8.fullMode=true

